name: Use secret has param

# Controls when the workflow will run
on:
  workflow_dispatch:
jobs:
  secret:
    runs-on: ubuntu-latest
    steps:      
      - name: secret
        env:
          USER: ${{ secrets.MY_USER }}
        run: echo "Hi, I'm "$USER""
  variable:
    runs-on: ubuntu-latest
    steps:
      - name: variable
        env: 
          USER: ${{ vars.USER }}
        run:  echo "Hi, I'm "$USER""
