# This is a basic workflow to help you get started with Actions

name: Introduce myself

# Controls when the workflow will run
on:
  workflow_dispatch:
env:
  nombre: "EVA"
jobs:
  my-name:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: say hi on shell with variable
        run: echo "Hi, I'm $nombre"
      - name: say hi on python with argument
        run: python hello-params.py "Eva"
      - name: say hi on python with argument passed with variable
        run: python hello-params.py $nombre
