# This is a basic workflow to help you get started with Actions

name: Hello world python!

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:        
        python-version: [3.5, 3.6, 3.7, 3.8] # Set the python versions to be installed and run of
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: execute py script
        run: python main.py
      
