name: Use secret has param

# Controls when the workflow will run
on:
  workflow_dispatch:
jobs:
  my-name:
    runs-on: ubuntu-latest
    steps:      
      - name: hello user
        env:
          USER: ${{ secrets.MY_USER }}
        run: echo "Hi, I'm "$USER""
